apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-sample
    app.kubernetes.io/part-of: purple-mermaid-app1
  name: nodejs-sample
  namespace: eyuen
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: nodejs-sample
status:
  loadBalancer: {}
